// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: uart_control_messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LoRa {

  /// <summary>Holder for reflection information generated from uart_control_messages.proto</summary>
  public static partial class UartControlMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for uart_control_messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UartControlMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cht1YXJ0X2NvbnRyb2xfbWVzc2FnZXMucHJvdG8aGmxvcmFfZGV2aWNlX21l",
            "c3NhZ2VzLnByb3RvGhVzaGFyZWQvbG9yYV9waHkucHJvdG8iMQoYQ2xlYXJN",
            "ZWFzdXJlbWVudHNDb21tYW5kEhUKDVNlbmRCb290QWZ0ZXIYASABKAgiwgIK",
            "C1VhcnRDb21tYW5kEiIKCHJ4Q29uZmlnGAEgASgLMg4uUmFkaW9SeENvbmZp",
            "Z0gAEiIKCHR4Q29uZmlnGAIgASgLMg4uUmFkaW9UeENvbmZpZ0gAEjMKE2Rl",
            "dmljZUNvbmZpZ3VyYXRpb24YAyABKAsyFC5EZXZpY2VDb25maWd1cmF0aW9u",
            "SAASKwoPcmVxdWVzdEJvb3RJbmZvGAQgASgLMhAuUmVxdWVzdEJvb3RJbmZv",
            "SAASPQoYY2xlYXJNZWFzdXJlbWVudHNDb21tYW5kGAUgASgLMhkuQ2xlYXJN",
            "ZWFzdXJlbWVudHNDb21tYW5kSAASJwoPdHJhbnNtaXRDb21tYW5kGAYgASgL",
            "MgwuTG9SYU1lc3NhZ2VIABIZChFkb05vdFByb3h5Q29tbWFuZBgIIAEoCEIG",
            "CgRCb2R5QgeqAgRMb1JhYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LoRa.LoraDeviceMessagesReflection.Descriptor, global::LoRa.LoraPhyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.ClearMeasurementsCommand), global::LoRa.ClearMeasurementsCommand.Parser, new[]{ "SendBootAfter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.UartCommand), global::LoRa.UartCommand.Parser, new[]{ "RxConfig", "TxConfig", "DeviceConfiguration", "RequestBootInfo", "ClearMeasurementsCommand", "TransmitCommand", "DoNotProxyCommand" }, new[]{ "Body" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClearMeasurementsCommand : pb::IMessage<ClearMeasurementsCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClearMeasurementsCommand> _parser = new pb::MessageParser<ClearMeasurementsCommand>(() => new ClearMeasurementsCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClearMeasurementsCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.UartControlMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClearMeasurementsCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClearMeasurementsCommand(ClearMeasurementsCommand other) : this() {
      sendBootAfter_ = other.sendBootAfter_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClearMeasurementsCommand Clone() {
      return new ClearMeasurementsCommand(this);
    }

    /// <summary>Field number for the "SendBootAfter" field.</summary>
    public const int SendBootAfterFieldNumber = 1;
    private bool sendBootAfter_;
    /// <summary>
    /// No content to report
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SendBootAfter {
      get { return sendBootAfter_; }
      set {
        sendBootAfter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClearMeasurementsCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClearMeasurementsCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SendBootAfter != other.SendBootAfter) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SendBootAfter != false) hash ^= SendBootAfter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SendBootAfter != false) {
        output.WriteRawTag(8);
        output.WriteBool(SendBootAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SendBootAfter != false) {
        output.WriteRawTag(8);
        output.WriteBool(SendBootAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SendBootAfter != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClearMeasurementsCommand other) {
      if (other == null) {
        return;
      }
      if (other.SendBootAfter != false) {
        SendBootAfter = other.SendBootAfter;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SendBootAfter = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SendBootAfter = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UartCommand : pb::IMessage<UartCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UartCommand> _parser = new pb::MessageParser<UartCommand>(() => new UartCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UartCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.UartControlMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UartCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UartCommand(UartCommand other) : this() {
      doNotProxyCommand_ = other.doNotProxyCommand_;
      switch (other.BodyCase) {
        case BodyOneofCase.RxConfig:
          RxConfig = other.RxConfig.Clone();
          break;
        case BodyOneofCase.TxConfig:
          TxConfig = other.TxConfig.Clone();
          break;
        case BodyOneofCase.DeviceConfiguration:
          DeviceConfiguration = other.DeviceConfiguration.Clone();
          break;
        case BodyOneofCase.RequestBootInfo:
          RequestBootInfo = other.RequestBootInfo.Clone();
          break;
        case BodyOneofCase.ClearMeasurementsCommand:
          ClearMeasurementsCommand = other.ClearMeasurementsCommand.Clone();
          break;
        case BodyOneofCase.TransmitCommand:
          TransmitCommand = other.TransmitCommand.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UartCommand Clone() {
      return new UartCommand(this);
    }

    /// <summary>Field number for the "rxConfig" field.</summary>
    public const int RxConfigFieldNumber = 1;
    /// <summary>
    /// Configure the gateway device over UART
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.RadioRxConfig RxConfig {
      get { return bodyCase_ == BodyOneofCase.RxConfig ? (global::LoRa.RadioRxConfig) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.RxConfig;
      }
    }

    /// <summary>Field number for the "txConfig" field.</summary>
    public const int TxConfigFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.RadioTxConfig TxConfig {
      get { return bodyCase_ == BodyOneofCase.TxConfig ? (global::LoRa.RadioTxConfig) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.TxConfig;
      }
    }

    /// <summary>Field number for the "deviceConfiguration" field.</summary>
    public const int DeviceConfigurationFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.DeviceConfiguration DeviceConfiguration {
      get { return bodyCase_ == BodyOneofCase.DeviceConfiguration ? (global::LoRa.DeviceConfiguration) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.DeviceConfiguration;
      }
    }

    /// <summary>Field number for the "requestBootInfo" field.</summary>
    public const int RequestBootInfoFieldNumber = 4;
    /// <summary>
    /// Request the info presented at boot
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.RequestBootInfo RequestBootInfo {
      get { return bodyCase_ == BodyOneofCase.RequestBootInfo ? (global::LoRa.RequestBootInfo) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.RequestBootInfo;
      }
    }

    /// <summary>Field number for the "clearMeasurementsCommand" field.</summary>
    public const int ClearMeasurementsCommandFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.ClearMeasurementsCommand ClearMeasurementsCommand {
      get { return bodyCase_ == BodyOneofCase.ClearMeasurementsCommand ? (global::LoRa.ClearMeasurementsCommand) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.ClearMeasurementsCommand;
      }
    }

    /// <summary>Field number for the "transmitCommand" field.</summary>
    public const int TransmitCommandFieldNumber = 6;
    /// <summary>
    /// Request a LoRa transmission - wraps similar commands as above
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.LoRaMessage TransmitCommand {
      get { return bodyCase_ == BodyOneofCase.TransmitCommand ? (global::LoRa.LoRaMessage) body_ : null; }
      set {
        body_ = value;
        bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.TransmitCommand;
      }
    }

    /// <summary>Field number for the "doNotProxyCommand" field.</summary>
    public const int DoNotProxyCommandFieldNumber = 8;
    private bool doNotProxyCommand_;
    /// <summary>
    /// Do not proxy the LoRa command - for debugging purposes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DoNotProxyCommand {
      get { return doNotProxyCommand_; }
      set {
        doNotProxyCommand_ = value;
      }
    }

    private object body_;
    /// <summary>Enum of possible cases for the "Body" oneof.</summary>
    public enum BodyOneofCase {
      None = 0,
      RxConfig = 1,
      TxConfig = 2,
      DeviceConfiguration = 3,
      RequestBootInfo = 4,
      ClearMeasurementsCommand = 5,
      TransmitCommand = 6,
    }
    private BodyOneofCase bodyCase_ = BodyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BodyOneofCase BodyCase {
      get { return bodyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBody() {
      bodyCase_ = BodyOneofCase.None;
      body_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UartCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UartCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RxConfig, other.RxConfig)) return false;
      if (!object.Equals(TxConfig, other.TxConfig)) return false;
      if (!object.Equals(DeviceConfiguration, other.DeviceConfiguration)) return false;
      if (!object.Equals(RequestBootInfo, other.RequestBootInfo)) return false;
      if (!object.Equals(ClearMeasurementsCommand, other.ClearMeasurementsCommand)) return false;
      if (!object.Equals(TransmitCommand, other.TransmitCommand)) return false;
      if (DoNotProxyCommand != other.DoNotProxyCommand) return false;
      if (BodyCase != other.BodyCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (bodyCase_ == BodyOneofCase.RxConfig) hash ^= RxConfig.GetHashCode();
      if (bodyCase_ == BodyOneofCase.TxConfig) hash ^= TxConfig.GetHashCode();
      if (bodyCase_ == BodyOneofCase.DeviceConfiguration) hash ^= DeviceConfiguration.GetHashCode();
      if (bodyCase_ == BodyOneofCase.RequestBootInfo) hash ^= RequestBootInfo.GetHashCode();
      if (bodyCase_ == BodyOneofCase.ClearMeasurementsCommand) hash ^= ClearMeasurementsCommand.GetHashCode();
      if (bodyCase_ == BodyOneofCase.TransmitCommand) hash ^= TransmitCommand.GetHashCode();
      if (DoNotProxyCommand != false) hash ^= DoNotProxyCommand.GetHashCode();
      hash ^= (int) bodyCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (bodyCase_ == BodyOneofCase.RxConfig) {
        output.WriteRawTag(10);
        output.WriteMessage(RxConfig);
      }
      if (bodyCase_ == BodyOneofCase.TxConfig) {
        output.WriteRawTag(18);
        output.WriteMessage(TxConfig);
      }
      if (bodyCase_ == BodyOneofCase.DeviceConfiguration) {
        output.WriteRawTag(26);
        output.WriteMessage(DeviceConfiguration);
      }
      if (bodyCase_ == BodyOneofCase.RequestBootInfo) {
        output.WriteRawTag(34);
        output.WriteMessage(RequestBootInfo);
      }
      if (bodyCase_ == BodyOneofCase.ClearMeasurementsCommand) {
        output.WriteRawTag(42);
        output.WriteMessage(ClearMeasurementsCommand);
      }
      if (bodyCase_ == BodyOneofCase.TransmitCommand) {
        output.WriteRawTag(50);
        output.WriteMessage(TransmitCommand);
      }
      if (DoNotProxyCommand != false) {
        output.WriteRawTag(64);
        output.WriteBool(DoNotProxyCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (bodyCase_ == BodyOneofCase.RxConfig) {
        output.WriteRawTag(10);
        output.WriteMessage(RxConfig);
      }
      if (bodyCase_ == BodyOneofCase.TxConfig) {
        output.WriteRawTag(18);
        output.WriteMessage(TxConfig);
      }
      if (bodyCase_ == BodyOneofCase.DeviceConfiguration) {
        output.WriteRawTag(26);
        output.WriteMessage(DeviceConfiguration);
      }
      if (bodyCase_ == BodyOneofCase.RequestBootInfo) {
        output.WriteRawTag(34);
        output.WriteMessage(RequestBootInfo);
      }
      if (bodyCase_ == BodyOneofCase.ClearMeasurementsCommand) {
        output.WriteRawTag(42);
        output.WriteMessage(ClearMeasurementsCommand);
      }
      if (bodyCase_ == BodyOneofCase.TransmitCommand) {
        output.WriteRawTag(50);
        output.WriteMessage(TransmitCommand);
      }
      if (DoNotProxyCommand != false) {
        output.WriteRawTag(64);
        output.WriteBool(DoNotProxyCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (bodyCase_ == BodyOneofCase.RxConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RxConfig);
      }
      if (bodyCase_ == BodyOneofCase.TxConfig) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TxConfig);
      }
      if (bodyCase_ == BodyOneofCase.DeviceConfiguration) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceConfiguration);
      }
      if (bodyCase_ == BodyOneofCase.RequestBootInfo) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestBootInfo);
      }
      if (bodyCase_ == BodyOneofCase.ClearMeasurementsCommand) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClearMeasurementsCommand);
      }
      if (bodyCase_ == BodyOneofCase.TransmitCommand) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransmitCommand);
      }
      if (DoNotProxyCommand != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UartCommand other) {
      if (other == null) {
        return;
      }
      if (other.DoNotProxyCommand != false) {
        DoNotProxyCommand = other.DoNotProxyCommand;
      }
      switch (other.BodyCase) {
        case BodyOneofCase.RxConfig:
          if (RxConfig == null) {
            RxConfig = new global::LoRa.RadioRxConfig();
          }
          RxConfig.MergeFrom(other.RxConfig);
          break;
        case BodyOneofCase.TxConfig:
          if (TxConfig == null) {
            TxConfig = new global::LoRa.RadioTxConfig();
          }
          TxConfig.MergeFrom(other.TxConfig);
          break;
        case BodyOneofCase.DeviceConfiguration:
          if (DeviceConfiguration == null) {
            DeviceConfiguration = new global::LoRa.DeviceConfiguration();
          }
          DeviceConfiguration.MergeFrom(other.DeviceConfiguration);
          break;
        case BodyOneofCase.RequestBootInfo:
          if (RequestBootInfo == null) {
            RequestBootInfo = new global::LoRa.RequestBootInfo();
          }
          RequestBootInfo.MergeFrom(other.RequestBootInfo);
          break;
        case BodyOneofCase.ClearMeasurementsCommand:
          if (ClearMeasurementsCommand == null) {
            ClearMeasurementsCommand = new global::LoRa.ClearMeasurementsCommand();
          }
          ClearMeasurementsCommand.MergeFrom(other.ClearMeasurementsCommand);
          break;
        case BodyOneofCase.TransmitCommand:
          if (TransmitCommand == null) {
            TransmitCommand = new global::LoRa.LoRaMessage();
          }
          TransmitCommand.MergeFrom(other.TransmitCommand);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::LoRa.RadioRxConfig subBuilder = new global::LoRa.RadioRxConfig();
            if (bodyCase_ == BodyOneofCase.RxConfig) {
              subBuilder.MergeFrom(RxConfig);
            }
            input.ReadMessage(subBuilder);
            RxConfig = subBuilder;
            break;
          }
          case 18: {
            global::LoRa.RadioTxConfig subBuilder = new global::LoRa.RadioTxConfig();
            if (bodyCase_ == BodyOneofCase.TxConfig) {
              subBuilder.MergeFrom(TxConfig);
            }
            input.ReadMessage(subBuilder);
            TxConfig = subBuilder;
            break;
          }
          case 26: {
            global::LoRa.DeviceConfiguration subBuilder = new global::LoRa.DeviceConfiguration();
            if (bodyCase_ == BodyOneofCase.DeviceConfiguration) {
              subBuilder.MergeFrom(DeviceConfiguration);
            }
            input.ReadMessage(subBuilder);
            DeviceConfiguration = subBuilder;
            break;
          }
          case 34: {
            global::LoRa.RequestBootInfo subBuilder = new global::LoRa.RequestBootInfo();
            if (bodyCase_ == BodyOneofCase.RequestBootInfo) {
              subBuilder.MergeFrom(RequestBootInfo);
            }
            input.ReadMessage(subBuilder);
            RequestBootInfo = subBuilder;
            break;
          }
          case 42: {
            global::LoRa.ClearMeasurementsCommand subBuilder = new global::LoRa.ClearMeasurementsCommand();
            if (bodyCase_ == BodyOneofCase.ClearMeasurementsCommand) {
              subBuilder.MergeFrom(ClearMeasurementsCommand);
            }
            input.ReadMessage(subBuilder);
            ClearMeasurementsCommand = subBuilder;
            break;
          }
          case 50: {
            global::LoRa.LoRaMessage subBuilder = new global::LoRa.LoRaMessage();
            if (bodyCase_ == BodyOneofCase.TransmitCommand) {
              subBuilder.MergeFrom(TransmitCommand);
            }
            input.ReadMessage(subBuilder);
            TransmitCommand = subBuilder;
            break;
          }
          case 64: {
            DoNotProxyCommand = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::LoRa.RadioRxConfig subBuilder = new global::LoRa.RadioRxConfig();
            if (bodyCase_ == BodyOneofCase.RxConfig) {
              subBuilder.MergeFrom(RxConfig);
            }
            input.ReadMessage(subBuilder);
            RxConfig = subBuilder;
            break;
          }
          case 18: {
            global::LoRa.RadioTxConfig subBuilder = new global::LoRa.RadioTxConfig();
            if (bodyCase_ == BodyOneofCase.TxConfig) {
              subBuilder.MergeFrom(TxConfig);
            }
            input.ReadMessage(subBuilder);
            TxConfig = subBuilder;
            break;
          }
          case 26: {
            global::LoRa.DeviceConfiguration subBuilder = new global::LoRa.DeviceConfiguration();
            if (bodyCase_ == BodyOneofCase.DeviceConfiguration) {
              subBuilder.MergeFrom(DeviceConfiguration);
            }
            input.ReadMessage(subBuilder);
            DeviceConfiguration = subBuilder;
            break;
          }
          case 34: {
            global::LoRa.RequestBootInfo subBuilder = new global::LoRa.RequestBootInfo();
            if (bodyCase_ == BodyOneofCase.RequestBootInfo) {
              subBuilder.MergeFrom(RequestBootInfo);
            }
            input.ReadMessage(subBuilder);
            RequestBootInfo = subBuilder;
            break;
          }
          case 42: {
            global::LoRa.ClearMeasurementsCommand subBuilder = new global::LoRa.ClearMeasurementsCommand();
            if (bodyCase_ == BodyOneofCase.ClearMeasurementsCommand) {
              subBuilder.MergeFrom(ClearMeasurementsCommand);
            }
            input.ReadMessage(subBuilder);
            ClearMeasurementsCommand = subBuilder;
            break;
          }
          case 50: {
            global::LoRa.LoRaMessage subBuilder = new global::LoRa.LoRaMessage();
            if (bodyCase_ == BodyOneofCase.TransmitCommand) {
              subBuilder.MergeFrom(TransmitCommand);
            }
            input.ReadMessage(subBuilder);
            TransmitCommand = subBuilder;
            break;
          }
          case 64: {
            DoNotProxyCommand = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
