// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: device_messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from device_messages.proto</summary>
public static partial class DeviceMessagesReflection {

  #region Descriptor
  /// <summary>File descriptor for device_messages.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DeviceMessagesReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVkZXZpY2VfbWVzc2FnZXMucHJvdG8iSAoHVmVyc2lvbhINCgVNYWpvchgB",
          "IAEoDRINCgVNaW5vchgCIAEoDRINCgVQYXRjaBgDIAEoDRIQCghSZXZpc2lv",
          "bhgEIAEoDSIxCghEZXZpY2VJZBILCgNJZDAYASABKA0SCwoDSWQxGAIgASgN",
          "EgsKA0lkMhgDIAEoDSKuAQoLTG9yYVJlY2VpdmUSDAoEU2l6ZRgBIAEoDRIM",
          "CgRSc3NpGAIgASgFEgsKA1NuchgDIAEoBRIWCg5TZXF1ZW5jZU51bWJlchgE",
          "IAEoDRIiChVJc01lYXN1cmVtZW50RnJhZ21lbnQYBSABKAhIAIgBARIPCgdT",
          "dWNjZXNzGAYgASgIEg8KB1BheWxvYWQYByABKAxCGAoWX0lzTWVhc3VyZW1l",
          "bnRGcmFnbWVudCKeAQoLQm9vdE1lc3NhZ2USIwoQRGV2aWNlSWRlbnRpZmll",
          "chgBIAEoCzIJLkRldmljZUlkEiEKD0Zpcm13YXJlVmVyc2lvbhgCIAEoCzII",
          "LlZlcnNpb24SDwoHQXBwTmFtZRgDIAEoCRIYChBNZWFzdXJlbWVudENvdW50",
          "GAQgASgNEhwKFE1lYXN1cmVtZW50c0Rpc2FibGVkGAUgASgIIiQKCkFja01l",
          "c3NhZ2USFgoOU2VxdWVuY2VOdW1iZXIYASABKA0iHwoMRGVidWdNZXNzYWdl",
          "Eg8KB3BheWxvYWQYASABKAwisQEKDFVhcnRSZXNwb25zZRIjCgtib290TWVz",
          "c2FnZRgBIAEoCzIMLkJvb3RNZXNzYWdlSAASIQoKYWNrTWVzc2FnZRgCIAEo",
          "CzILLkFja01lc3NhZ2VIABIqChJsb3JhUmVjZWl2ZU1lc3NhZ2UYAyABKAsy",
          "DC5Mb3JhUmVjZWl2ZUgAEiUKDGRlYnVnTWVzc2FnZRgEIAEoCzINLkRlYnVn",
          "TWVzc2FnZUgAQgYKBEJvZHliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Version), global::Version.Parser, new[]{ "Major", "Minor", "Patch", "Revision" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DeviceId), global::DeviceId.Parser, new[]{ "Id0", "Id1", "Id2" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LoraReceive), global::LoraReceive.Parser, new[]{ "Size", "Rssi", "Snr", "SequenceNumber", "IsMeasurementFragment", "Success", "Payload" }, new[]{ "IsMeasurementFragment" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BootMessage), global::BootMessage.Parser, new[]{ "DeviceIdentifier", "FirmwareVersion", "AppName", "MeasurementCount", "MeasurementsDisabled" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AckMessage), global::AckMessage.Parser, new[]{ "SequenceNumber" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DebugMessage), global::DebugMessage.Parser, new[]{ "Payload" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::UartResponse), global::UartResponse.Parser, new[]{ "BootMessage", "AckMessage", "LoraReceiveMessage", "DebugMessage" }, new[]{ "Body" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Version : pb::IMessage<Version>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Version> _parser = new pb::MessageParser<Version>(() => new Version());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Version> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Version() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Version(Version other) : this() {
    major_ = other.major_;
    minor_ = other.minor_;
    patch_ = other.patch_;
    revision_ = other.revision_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Version Clone() {
    return new Version(this);
  }

  /// <summary>Field number for the "Major" field.</summary>
  public const int MajorFieldNumber = 1;
  private uint major_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Major {
    get { return major_; }
    set {
      major_ = value;
    }
  }

  /// <summary>Field number for the "Minor" field.</summary>
  public const int MinorFieldNumber = 2;
  private uint minor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Minor {
    get { return minor_; }
    set {
      minor_ = value;
    }
  }

  /// <summary>Field number for the "Patch" field.</summary>
  public const int PatchFieldNumber = 3;
  private uint patch_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Patch {
    get { return patch_; }
    set {
      patch_ = value;
    }
  }

  /// <summary>Field number for the "Revision" field.</summary>
  public const int RevisionFieldNumber = 4;
  private uint revision_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Revision {
    get { return revision_; }
    set {
      revision_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Version);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Version other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Major != other.Major) return false;
    if (Minor != other.Minor) return false;
    if (Patch != other.Patch) return false;
    if (Revision != other.Revision) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Major != 0) hash ^= Major.GetHashCode();
    if (Minor != 0) hash ^= Minor.GetHashCode();
    if (Patch != 0) hash ^= Patch.GetHashCode();
    if (Revision != 0) hash ^= Revision.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Major != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Major);
    }
    if (Minor != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Minor);
    }
    if (Patch != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Patch);
    }
    if (Revision != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Revision);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Major != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Major);
    }
    if (Minor != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Minor);
    }
    if (Patch != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Patch);
    }
    if (Revision != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Revision);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Major != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Major);
    }
    if (Minor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Minor);
    }
    if (Patch != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Patch);
    }
    if (Revision != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Revision);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Version other) {
    if (other == null) {
      return;
    }
    if (other.Major != 0) {
      Major = other.Major;
    }
    if (other.Minor != 0) {
      Minor = other.Minor;
    }
    if (other.Patch != 0) {
      Patch = other.Patch;
    }
    if (other.Revision != 0) {
      Revision = other.Revision;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Major = input.ReadUInt32();
          break;
        }
        case 16: {
          Minor = input.ReadUInt32();
          break;
        }
        case 24: {
          Patch = input.ReadUInt32();
          break;
        }
        case 32: {
          Revision = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Major = input.ReadUInt32();
          break;
        }
        case 16: {
          Minor = input.ReadUInt32();
          break;
        }
        case 24: {
          Patch = input.ReadUInt32();
          break;
        }
        case 32: {
          Revision = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DeviceId : pb::IMessage<DeviceId>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DeviceId> _parser = new pb::MessageParser<DeviceId>(() => new DeviceId());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DeviceId> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DeviceId() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DeviceId(DeviceId other) : this() {
    id0_ = other.id0_;
    id1_ = other.id1_;
    id2_ = other.id2_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DeviceId Clone() {
    return new DeviceId(this);
  }

  /// <summary>Field number for the "Id0" field.</summary>
  public const int Id0FieldNumber = 1;
  private uint id0_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id0 {
    get { return id0_; }
    set {
      id0_ = value;
    }
  }

  /// <summary>Field number for the "Id1" field.</summary>
  public const int Id1FieldNumber = 2;
  private uint id1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id1 {
    get { return id1_; }
    set {
      id1_ = value;
    }
  }

  /// <summary>Field number for the "Id2" field.</summary>
  public const int Id2FieldNumber = 3;
  private uint id2_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id2 {
    get { return id2_; }
    set {
      id2_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DeviceId);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DeviceId other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id0 != other.Id0) return false;
    if (Id1 != other.Id1) return false;
    if (Id2 != other.Id2) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id0 != 0) hash ^= Id0.GetHashCode();
    if (Id1 != 0) hash ^= Id1.GetHashCode();
    if (Id2 != 0) hash ^= Id2.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id0 != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id0);
    }
    if (Id1 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Id1);
    }
    if (Id2 != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Id2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id0 != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id0);
    }
    if (Id1 != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Id1);
    }
    if (Id2 != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Id2);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id0 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id0);
    }
    if (Id1 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id1);
    }
    if (Id2 != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id2);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DeviceId other) {
    if (other == null) {
      return;
    }
    if (other.Id0 != 0) {
      Id0 = other.Id0;
    }
    if (other.Id1 != 0) {
      Id1 = other.Id1;
    }
    if (other.Id2 != 0) {
      Id2 = other.Id2;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id0 = input.ReadUInt32();
          break;
        }
        case 16: {
          Id1 = input.ReadUInt32();
          break;
        }
        case 24: {
          Id2 = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id0 = input.ReadUInt32();
          break;
        }
        case 16: {
          Id1 = input.ReadUInt32();
          break;
        }
        case 24: {
          Id2 = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LoraReceive : pb::IMessage<LoraReceive>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LoraReceive> _parser = new pb::MessageParser<LoraReceive>(() => new LoraReceive());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LoraReceive> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoraReceive() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoraReceive(LoraReceive other) : this() {
    _hasBits0 = other._hasBits0;
    size_ = other.size_;
    rssi_ = other.rssi_;
    snr_ = other.snr_;
    sequenceNumber_ = other.sequenceNumber_;
    isMeasurementFragment_ = other.isMeasurementFragment_;
    success_ = other.success_;
    payload_ = other.payload_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LoraReceive Clone() {
    return new LoraReceive(this);
  }

  /// <summary>Field number for the "Size" field.</summary>
  public const int SizeFieldNumber = 1;
  private uint size_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Size {
    get { return size_; }
    set {
      size_ = value;
    }
  }

  /// <summary>Field number for the "Rssi" field.</summary>
  public const int RssiFieldNumber = 2;
  private int rssi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Rssi {
    get { return rssi_; }
    set {
      rssi_ = value;
    }
  }

  /// <summary>Field number for the "Snr" field.</summary>
  public const int SnrFieldNumber = 3;
  private int snr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Snr {
    get { return snr_; }
    set {
      snr_ = value;
    }
  }

  /// <summary>Field number for the "SequenceNumber" field.</summary>
  public const int SequenceNumberFieldNumber = 4;
  private uint sequenceNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SequenceNumber {
    get { return sequenceNumber_; }
    set {
      sequenceNumber_ = value;
    }
  }

  /// <summary>Field number for the "IsMeasurementFragment" field.</summary>
  public const int IsMeasurementFragmentFieldNumber = 5;
  private bool isMeasurementFragment_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsMeasurementFragment {
    get { if ((_hasBits0 & 1) != 0) { return isMeasurementFragment_; } else { return false; } }
    set {
      _hasBits0 |= 1;
      isMeasurementFragment_ = value;
    }
  }
  /// <summary>Gets whether the "IsMeasurementFragment" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasIsMeasurementFragment {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "IsMeasurementFragment" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearIsMeasurementFragment() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "Success" field.</summary>
  public const int SuccessFieldNumber = 6;
  private bool success_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Success {
    get { return success_; }
    set {
      success_ = value;
    }
  }

  /// <summary>Field number for the "Payload" field.</summary>
  public const int PayloadFieldNumber = 7;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LoraReceive);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LoraReceive other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Size != other.Size) return false;
    if (Rssi != other.Rssi) return false;
    if (Snr != other.Snr) return false;
    if (SequenceNumber != other.SequenceNumber) return false;
    if (IsMeasurementFragment != other.IsMeasurementFragment) return false;
    if (Success != other.Success) return false;
    if (Payload != other.Payload) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Size != 0) hash ^= Size.GetHashCode();
    if (Rssi != 0) hash ^= Rssi.GetHashCode();
    if (Snr != 0) hash ^= Snr.GetHashCode();
    if (SequenceNumber != 0) hash ^= SequenceNumber.GetHashCode();
    if (HasIsMeasurementFragment) hash ^= IsMeasurementFragment.GetHashCode();
    if (Success != false) hash ^= Success.GetHashCode();
    if (Payload.Length != 0) hash ^= Payload.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Size != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Size);
    }
    if (Rssi != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Rssi);
    }
    if (Snr != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Snr);
    }
    if (SequenceNumber != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(SequenceNumber);
    }
    if (HasIsMeasurementFragment) {
      output.WriteRawTag(40);
      output.WriteBool(IsMeasurementFragment);
    }
    if (Success != false) {
      output.WriteRawTag(48);
      output.WriteBool(Success);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(58);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Size != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Size);
    }
    if (Rssi != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Rssi);
    }
    if (Snr != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Snr);
    }
    if (SequenceNumber != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(SequenceNumber);
    }
    if (HasIsMeasurementFragment) {
      output.WriteRawTag(40);
      output.WriteBool(IsMeasurementFragment);
    }
    if (Success != false) {
      output.WriteRawTag(48);
      output.WriteBool(Success);
    }
    if (Payload.Length != 0) {
      output.WriteRawTag(58);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Size != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Size);
    }
    if (Rssi != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rssi);
    }
    if (Snr != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Snr);
    }
    if (SequenceNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNumber);
    }
    if (HasIsMeasurementFragment) {
      size += 1 + 1;
    }
    if (Success != false) {
      size += 1 + 1;
    }
    if (Payload.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LoraReceive other) {
    if (other == null) {
      return;
    }
    if (other.Size != 0) {
      Size = other.Size;
    }
    if (other.Rssi != 0) {
      Rssi = other.Rssi;
    }
    if (other.Snr != 0) {
      Snr = other.Snr;
    }
    if (other.SequenceNumber != 0) {
      SequenceNumber = other.SequenceNumber;
    }
    if (other.HasIsMeasurementFragment) {
      IsMeasurementFragment = other.IsMeasurementFragment;
    }
    if (other.Success != false) {
      Success = other.Success;
    }
    if (other.Payload.Length != 0) {
      Payload = other.Payload;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Size = input.ReadUInt32();
          break;
        }
        case 16: {
          Rssi = input.ReadInt32();
          break;
        }
        case 24: {
          Snr = input.ReadInt32();
          break;
        }
        case 32: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
        case 40: {
          IsMeasurementFragment = input.ReadBool();
          break;
        }
        case 48: {
          Success = input.ReadBool();
          break;
        }
        case 58: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Size = input.ReadUInt32();
          break;
        }
        case 16: {
          Rssi = input.ReadInt32();
          break;
        }
        case 24: {
          Snr = input.ReadInt32();
          break;
        }
        case 32: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
        case 40: {
          IsMeasurementFragment = input.ReadBool();
          break;
        }
        case 48: {
          Success = input.ReadBool();
          break;
        }
        case 58: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class BootMessage : pb::IMessage<BootMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BootMessage> _parser = new pb::MessageParser<BootMessage>(() => new BootMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BootMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BootMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BootMessage(BootMessage other) : this() {
    deviceIdentifier_ = other.deviceIdentifier_ != null ? other.deviceIdentifier_.Clone() : null;
    firmwareVersion_ = other.firmwareVersion_ != null ? other.firmwareVersion_.Clone() : null;
    appName_ = other.appName_;
    measurementCount_ = other.measurementCount_;
    measurementsDisabled_ = other.measurementsDisabled_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BootMessage Clone() {
    return new BootMessage(this);
  }

  /// <summary>Field number for the "DeviceIdentifier" field.</summary>
  public const int DeviceIdentifierFieldNumber = 1;
  private global::DeviceId deviceIdentifier_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DeviceId DeviceIdentifier {
    get { return deviceIdentifier_; }
    set {
      deviceIdentifier_ = value;
    }
  }

  /// <summary>Field number for the "FirmwareVersion" field.</summary>
  public const int FirmwareVersionFieldNumber = 2;
  private global::Version firmwareVersion_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Version FirmwareVersion {
    get { return firmwareVersion_; }
    set {
      firmwareVersion_ = value;
    }
  }

  /// <summary>Field number for the "AppName" field.</summary>
  public const int AppNameFieldNumber = 3;
  private string appName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AppName {
    get { return appName_; }
    set {
      appName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "MeasurementCount" field.</summary>
  public const int MeasurementCountFieldNumber = 4;
  private uint measurementCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MeasurementCount {
    get { return measurementCount_; }
    set {
      measurementCount_ = value;
    }
  }

  /// <summary>Field number for the "MeasurementsDisabled" field.</summary>
  public const int MeasurementsDisabledFieldNumber = 5;
  private bool measurementsDisabled_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool MeasurementsDisabled {
    get { return measurementsDisabled_; }
    set {
      measurementsDisabled_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BootMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BootMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(DeviceIdentifier, other.DeviceIdentifier)) return false;
    if (!object.Equals(FirmwareVersion, other.FirmwareVersion)) return false;
    if (AppName != other.AppName) return false;
    if (MeasurementCount != other.MeasurementCount) return false;
    if (MeasurementsDisabled != other.MeasurementsDisabled) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (deviceIdentifier_ != null) hash ^= DeviceIdentifier.GetHashCode();
    if (firmwareVersion_ != null) hash ^= FirmwareVersion.GetHashCode();
    if (AppName.Length != 0) hash ^= AppName.GetHashCode();
    if (MeasurementCount != 0) hash ^= MeasurementCount.GetHashCode();
    if (MeasurementsDisabled != false) hash ^= MeasurementsDisabled.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (deviceIdentifier_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DeviceIdentifier);
    }
    if (firmwareVersion_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(FirmwareVersion);
    }
    if (AppName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AppName);
    }
    if (MeasurementCount != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MeasurementCount);
    }
    if (MeasurementsDisabled != false) {
      output.WriteRawTag(40);
      output.WriteBool(MeasurementsDisabled);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (deviceIdentifier_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(DeviceIdentifier);
    }
    if (firmwareVersion_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(FirmwareVersion);
    }
    if (AppName.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AppName);
    }
    if (MeasurementCount != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MeasurementCount);
    }
    if (MeasurementsDisabled != false) {
      output.WriteRawTag(40);
      output.WriteBool(MeasurementsDisabled);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (deviceIdentifier_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceIdentifier);
    }
    if (firmwareVersion_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FirmwareVersion);
    }
    if (AppName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AppName);
    }
    if (MeasurementCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MeasurementCount);
    }
    if (MeasurementsDisabled != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BootMessage other) {
    if (other == null) {
      return;
    }
    if (other.deviceIdentifier_ != null) {
      if (deviceIdentifier_ == null) {
        DeviceIdentifier = new global::DeviceId();
      }
      DeviceIdentifier.MergeFrom(other.DeviceIdentifier);
    }
    if (other.firmwareVersion_ != null) {
      if (firmwareVersion_ == null) {
        FirmwareVersion = new global::Version();
      }
      FirmwareVersion.MergeFrom(other.FirmwareVersion);
    }
    if (other.AppName.Length != 0) {
      AppName = other.AppName;
    }
    if (other.MeasurementCount != 0) {
      MeasurementCount = other.MeasurementCount;
    }
    if (other.MeasurementsDisabled != false) {
      MeasurementsDisabled = other.MeasurementsDisabled;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (deviceIdentifier_ == null) {
            DeviceIdentifier = new global::DeviceId();
          }
          input.ReadMessage(DeviceIdentifier);
          break;
        }
        case 18: {
          if (firmwareVersion_ == null) {
            FirmwareVersion = new global::Version();
          }
          input.ReadMessage(FirmwareVersion);
          break;
        }
        case 26: {
          AppName = input.ReadString();
          break;
        }
        case 32: {
          MeasurementCount = input.ReadUInt32();
          break;
        }
        case 40: {
          MeasurementsDisabled = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (deviceIdentifier_ == null) {
            DeviceIdentifier = new global::DeviceId();
          }
          input.ReadMessage(DeviceIdentifier);
          break;
        }
        case 18: {
          if (firmwareVersion_ == null) {
            FirmwareVersion = new global::Version();
          }
          input.ReadMessage(FirmwareVersion);
          break;
        }
        case 26: {
          AppName = input.ReadString();
          break;
        }
        case 32: {
          MeasurementCount = input.ReadUInt32();
          break;
        }
        case 40: {
          MeasurementsDisabled = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class AckMessage : pb::IMessage<AckMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AckMessage> _parser = new pb::MessageParser<AckMessage>(() => new AckMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AckMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AckMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AckMessage(AckMessage other) : this() {
    sequenceNumber_ = other.sequenceNumber_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AckMessage Clone() {
    return new AckMessage(this);
  }

  /// <summary>Field number for the "SequenceNumber" field.</summary>
  public const int SequenceNumberFieldNumber = 1;
  private uint sequenceNumber_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SequenceNumber {
    get { return sequenceNumber_; }
    set {
      sequenceNumber_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AckMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AckMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SequenceNumber != other.SequenceNumber) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SequenceNumber != 0) hash ^= SequenceNumber.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SequenceNumber != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(SequenceNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SequenceNumber != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(SequenceNumber);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SequenceNumber != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SequenceNumber);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AckMessage other) {
    if (other == null) {
      return;
    }
    if (other.SequenceNumber != 0) {
      SequenceNumber = other.SequenceNumber;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          SequenceNumber = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DebugMessage : pb::IMessage<DebugMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DebugMessage> _parser = new pb::MessageParser<DebugMessage>(() => new DebugMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DebugMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DebugMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DebugMessage(DebugMessage other) : this() {
    payload_ = other.payload_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DebugMessage Clone() {
    return new DebugMessage(this);
  }

  /// <summary>Field number for the "payload" field.</summary>
  public const int PayloadFieldNumber = 1;
  private pb::ByteString payload_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString Payload {
    get { return payload_; }
    set {
      payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DebugMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DebugMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Payload != other.Payload) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Payload.Length != 0) hash ^= Payload.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Payload.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Payload.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(Payload);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Payload.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DebugMessage other) {
    if (other == null) {
      return;
    }
    if (other.Payload.Length != 0) {
      Payload = other.Payload;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Payload = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
/// The main message container
/// </summary>
public sealed partial class UartResponse : pb::IMessage<UartResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UartResponse> _parser = new pb::MessageParser<UartResponse>(() => new UartResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UartResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DeviceMessagesReflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UartResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UartResponse(UartResponse other) : this() {
    switch (other.BodyCase) {
      case BodyOneofCase.BootMessage:
        BootMessage = other.BootMessage.Clone();
        break;
      case BodyOneofCase.AckMessage:
        AckMessage = other.AckMessage.Clone();
        break;
      case BodyOneofCase.LoraReceiveMessage:
        LoraReceiveMessage = other.LoraReceiveMessage.Clone();
        break;
      case BodyOneofCase.DebugMessage:
        DebugMessage = other.DebugMessage.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UartResponse Clone() {
    return new UartResponse(this);
  }

  /// <summary>Field number for the "bootMessage" field.</summary>
  public const int BootMessageFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::BootMessage BootMessage {
    get { return bodyCase_ == BodyOneofCase.BootMessage ? (global::BootMessage) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.BootMessage;
    }
  }

  /// <summary>Field number for the "ackMessage" field.</summary>
  public const int AckMessageFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AckMessage AckMessage {
    get { return bodyCase_ == BodyOneofCase.AckMessage ? (global::AckMessage) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.AckMessage;
    }
  }

  /// <summary>Field number for the "loraReceiveMessage" field.</summary>
  public const int LoraReceiveMessageFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LoraReceive LoraReceiveMessage {
    get { return bodyCase_ == BodyOneofCase.LoraReceiveMessage ? (global::LoraReceive) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.LoraReceiveMessage;
    }
  }

  /// <summary>Field number for the "debugMessage" field.</summary>
  public const int DebugMessageFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DebugMessage DebugMessage {
    get { return bodyCase_ == BodyOneofCase.DebugMessage ? (global::DebugMessage) body_ : null; }
    set {
      body_ = value;
      bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.DebugMessage;
    }
  }

  private object body_;
  /// <summary>Enum of possible cases for the "Body" oneof.</summary>
  public enum BodyOneofCase {
    None = 0,
    BootMessage = 1,
    AckMessage = 2,
    LoraReceiveMessage = 3,
    DebugMessage = 4,
  }
  private BodyOneofCase bodyCase_ = BodyOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BodyOneofCase BodyCase {
    get { return bodyCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearBody() {
    bodyCase_ = BodyOneofCase.None;
    body_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UartResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UartResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(BootMessage, other.BootMessage)) return false;
    if (!object.Equals(AckMessage, other.AckMessage)) return false;
    if (!object.Equals(LoraReceiveMessage, other.LoraReceiveMessage)) return false;
    if (!object.Equals(DebugMessage, other.DebugMessage)) return false;
    if (BodyCase != other.BodyCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (bodyCase_ == BodyOneofCase.BootMessage) hash ^= BootMessage.GetHashCode();
    if (bodyCase_ == BodyOneofCase.AckMessage) hash ^= AckMessage.GetHashCode();
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) hash ^= LoraReceiveMessage.GetHashCode();
    if (bodyCase_ == BodyOneofCase.DebugMessage) hash ^= DebugMessage.GetHashCode();
    hash ^= (int) bodyCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (bodyCase_ == BodyOneofCase.BootMessage) {
      output.WriteRawTag(10);
      output.WriteMessage(BootMessage);
    }
    if (bodyCase_ == BodyOneofCase.AckMessage) {
      output.WriteRawTag(18);
      output.WriteMessage(AckMessage);
    }
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
      output.WriteRawTag(26);
      output.WriteMessage(LoraReceiveMessage);
    }
    if (bodyCase_ == BodyOneofCase.DebugMessage) {
      output.WriteRawTag(34);
      output.WriteMessage(DebugMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (bodyCase_ == BodyOneofCase.BootMessage) {
      output.WriteRawTag(10);
      output.WriteMessage(BootMessage);
    }
    if (bodyCase_ == BodyOneofCase.AckMessage) {
      output.WriteRawTag(18);
      output.WriteMessage(AckMessage);
    }
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
      output.WriteRawTag(26);
      output.WriteMessage(LoraReceiveMessage);
    }
    if (bodyCase_ == BodyOneofCase.DebugMessage) {
      output.WriteRawTag(34);
      output.WriteMessage(DebugMessage);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (bodyCase_ == BodyOneofCase.BootMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BootMessage);
    }
    if (bodyCase_ == BodyOneofCase.AckMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(AckMessage);
    }
    if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoraReceiveMessage);
    }
    if (bodyCase_ == BodyOneofCase.DebugMessage) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DebugMessage);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UartResponse other) {
    if (other == null) {
      return;
    }
    switch (other.BodyCase) {
      case BodyOneofCase.BootMessage:
        if (BootMessage == null) {
          BootMessage = new global::BootMessage();
        }
        BootMessage.MergeFrom(other.BootMessage);
        break;
      case BodyOneofCase.AckMessage:
        if (AckMessage == null) {
          AckMessage = new global::AckMessage();
        }
        AckMessage.MergeFrom(other.AckMessage);
        break;
      case BodyOneofCase.LoraReceiveMessage:
        if (LoraReceiveMessage == null) {
          LoraReceiveMessage = new global::LoraReceive();
        }
        LoraReceiveMessage.MergeFrom(other.LoraReceiveMessage);
        break;
      case BodyOneofCase.DebugMessage:
        if (DebugMessage == null) {
          DebugMessage = new global::DebugMessage();
        }
        DebugMessage.MergeFrom(other.DebugMessage);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          global::BootMessage subBuilder = new global::BootMessage();
          if (bodyCase_ == BodyOneofCase.BootMessage) {
            subBuilder.MergeFrom(BootMessage);
          }
          input.ReadMessage(subBuilder);
          BootMessage = subBuilder;
          break;
        }
        case 18: {
          global::AckMessage subBuilder = new global::AckMessage();
          if (bodyCase_ == BodyOneofCase.AckMessage) {
            subBuilder.MergeFrom(AckMessage);
          }
          input.ReadMessage(subBuilder);
          AckMessage = subBuilder;
          break;
        }
        case 26: {
          global::LoraReceive subBuilder = new global::LoraReceive();
          if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
            subBuilder.MergeFrom(LoraReceiveMessage);
          }
          input.ReadMessage(subBuilder);
          LoraReceiveMessage = subBuilder;
          break;
        }
        case 34: {
          global::DebugMessage subBuilder = new global::DebugMessage();
          if (bodyCase_ == BodyOneofCase.DebugMessage) {
            subBuilder.MergeFrom(DebugMessage);
          }
          input.ReadMessage(subBuilder);
          DebugMessage = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          global::BootMessage subBuilder = new global::BootMessage();
          if (bodyCase_ == BodyOneofCase.BootMessage) {
            subBuilder.MergeFrom(BootMessage);
          }
          input.ReadMessage(subBuilder);
          BootMessage = subBuilder;
          break;
        }
        case 18: {
          global::AckMessage subBuilder = new global::AckMessage();
          if (bodyCase_ == BodyOneofCase.AckMessage) {
            subBuilder.MergeFrom(AckMessage);
          }
          input.ReadMessage(subBuilder);
          AckMessage = subBuilder;
          break;
        }
        case 26: {
          global::LoraReceive subBuilder = new global::LoraReceive();
          if (bodyCase_ == BodyOneofCase.LoraReceiveMessage) {
            subBuilder.MergeFrom(LoraReceiveMessage);
          }
          input.ReadMessage(subBuilder);
          LoraReceiveMessage = subBuilder;
          break;
        }
        case 34: {
          global::DebugMessage subBuilder = new global::DebugMessage();
          if (bodyCase_ == BodyOneofCase.DebugMessage) {
            subBuilder.MergeFrom(DebugMessage);
          }
          input.ReadMessage(subBuilder);
          DebugMessage = subBuilder;
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
