// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shared/experiment_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LoRa {

  /// <summary>Holder for reflection information generated from shared/experiment_config.proto</summary>
  public static partial class ExperimentConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for shared/experiment_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExperimentConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zaGFyZWQvZXhwZXJpbWVudF9jb25maWcucHJvdG8iUQoVU2VxdWVuY2VS",
            "ZXF1ZXN0Q29uZmlnEhQKDE1lc3NhZ2VDb3VudBgBIAEoDRIQCghJbnRlcnZh",
            "bBgCIAEoDRIQCghEZXZpY2VJZBgDIAEoDSJNChVTcHJlYWRpbmdGYWN0b3JD",
            "b25maWcSGQoRc3ByZWFkaW5nRmFjdG9yUngYASABKA0SGQoRc3ByZWFkaW5n",
            "RmFjdG9yVHgYAiABKA0qywEKC0NvbW1hbmRUeXBlEhEKDUNvbmZpZ3VyYXRp",
            "b24QABINCglNdWx0aUNhc3QQARIQCgxNdWx0aUNhc3RBY2sQAhILCgdVbmlD",
            "YXN0EAMSDgoKVW5pQ2FzdEFjaxAEEhwKGE1lYXN1cmVtZW50U3RyZWFtUmVx",
            "dWVzdBAFEiIKHk1lYXN1cmVtZW50U3RyZWFtRnJhZ21lbnRSZXBseRAGEhMK",
            "D1NlcXVlbmNlUmVxdWVzdBAHEhQKEFNlcXVlbmNlUmVzcG9uc2UQCEIHqgIE",
            "TG9SYWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LoRa.CommandType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.SequenceRequestConfig), global::LoRa.SequenceRequestConfig.Parser, new[]{ "MessageCount", "Interval", "DeviceId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.SpreadingFactorConfig), global::LoRa.SpreadingFactorConfig.Parser, new[]{ "SpreadingFactorRx", "SpreadingFactorTx" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CommandType {
    [pbr::OriginalName("Configuration")] Configuration = 0,
    [pbr::OriginalName("MultiCast")] MultiCast = 1,
    [pbr::OriginalName("MultiCastAck")] MultiCastAck = 2,
    [pbr::OriginalName("UniCast")] UniCast = 3,
    [pbr::OriginalName("UniCastAck")] UniCastAck = 4,
    [pbr::OriginalName("MeasurementStreamRequest")] MeasurementStreamRequest = 5,
    [pbr::OriginalName("MeasurementStreamFragmentReply")] MeasurementStreamFragmentReply = 6,
    [pbr::OriginalName("SequenceRequest")] SequenceRequest = 7,
    [pbr::OriginalName("SequenceResponse")] SequenceResponse = 8,
  }

  #endregion

  #region Messages
  public sealed partial class SequenceRequestConfig : pb::IMessage<SequenceRequestConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SequenceRequestConfig> _parser = new pb::MessageParser<SequenceRequestConfig>(() => new SequenceRequestConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SequenceRequestConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequenceRequestConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequenceRequestConfig(SequenceRequestConfig other) : this() {
      messageCount_ = other.messageCount_;
      interval_ = other.interval_;
      deviceId_ = other.deviceId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequenceRequestConfig Clone() {
      return new SequenceRequestConfig(this);
    }

    /// <summary>Field number for the "MessageCount" field.</summary>
    public const int MessageCountFieldNumber = 1;
    private uint messageCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MessageCount {
      get { return messageCount_; }
      set {
        messageCount_ = value;
      }
    }

    /// <summary>Field number for the "Interval" field.</summary>
    public const int IntervalFieldNumber = 2;
    private uint interval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Interval {
      get { return interval_; }
      set {
        interval_ = value;
      }
    }

    /// <summary>Field number for the "DeviceId" field.</summary>
    public const int DeviceIdFieldNumber = 3;
    private uint deviceId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SequenceRequestConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SequenceRequestConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageCount != other.MessageCount) return false;
      if (Interval != other.Interval) return false;
      if (DeviceId != other.DeviceId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageCount != 0) hash ^= MessageCount.GetHashCode();
      if (Interval != 0) hash ^= Interval.GetHashCode();
      if (DeviceId != 0) hash ^= DeviceId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageCount != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MessageCount);
      }
      if (Interval != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Interval);
      }
      if (DeviceId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DeviceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageCount != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MessageCount);
      }
      if (Interval != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Interval);
      }
      if (DeviceId != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DeviceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MessageCount);
      }
      if (Interval != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Interval);
      }
      if (DeviceId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeviceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SequenceRequestConfig other) {
      if (other == null) {
        return;
      }
      if (other.MessageCount != 0) {
        MessageCount = other.MessageCount;
      }
      if (other.Interval != 0) {
        Interval = other.Interval;
      }
      if (other.DeviceId != 0) {
        DeviceId = other.DeviceId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageCount = input.ReadUInt32();
            break;
          }
          case 16: {
            Interval = input.ReadUInt32();
            break;
          }
          case 24: {
            DeviceId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageCount = input.ReadUInt32();
            break;
          }
          case 16: {
            Interval = input.ReadUInt32();
            break;
          }
          case 24: {
            DeviceId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SpreadingFactorConfig : pb::IMessage<SpreadingFactorConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SpreadingFactorConfig> _parser = new pb::MessageParser<SpreadingFactorConfig>(() => new SpreadingFactorConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SpreadingFactorConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpreadingFactorConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpreadingFactorConfig(SpreadingFactorConfig other) : this() {
      spreadingFactorRx_ = other.spreadingFactorRx_;
      spreadingFactorTx_ = other.spreadingFactorTx_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SpreadingFactorConfig Clone() {
      return new SpreadingFactorConfig(this);
    }

    /// <summary>Field number for the "spreadingFactorRx" field.</summary>
    public const int SpreadingFactorRxFieldNumber = 1;
    private uint spreadingFactorRx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SpreadingFactorRx {
      get { return spreadingFactorRx_; }
      set {
        spreadingFactorRx_ = value;
      }
    }

    /// <summary>Field number for the "spreadingFactorTx" field.</summary>
    public const int SpreadingFactorTxFieldNumber = 2;
    private uint spreadingFactorTx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SpreadingFactorTx {
      get { return spreadingFactorTx_; }
      set {
        spreadingFactorTx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SpreadingFactorConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SpreadingFactorConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SpreadingFactorRx != other.SpreadingFactorRx) return false;
      if (SpreadingFactorTx != other.SpreadingFactorTx) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SpreadingFactorRx != 0) hash ^= SpreadingFactorRx.GetHashCode();
      if (SpreadingFactorTx != 0) hash ^= SpreadingFactorTx.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SpreadingFactorRx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SpreadingFactorRx);
      }
      if (SpreadingFactorTx != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SpreadingFactorTx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SpreadingFactorRx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(SpreadingFactorRx);
      }
      if (SpreadingFactorTx != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SpreadingFactorTx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SpreadingFactorRx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SpreadingFactorRx);
      }
      if (SpreadingFactorTx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SpreadingFactorTx);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SpreadingFactorConfig other) {
      if (other == null) {
        return;
      }
      if (other.SpreadingFactorRx != 0) {
        SpreadingFactorRx = other.SpreadingFactorRx;
      }
      if (other.SpreadingFactorTx != 0) {
        SpreadingFactorTx = other.SpreadingFactorTx;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SpreadingFactorRx = input.ReadUInt32();
            break;
          }
          case 16: {
            SpreadingFactorTx = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SpreadingFactorRx = input.ReadUInt32();
            break;
          }
          case 16: {
            SpreadingFactorTx = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
