// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shared/experiment_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LoRa {

  /// <summary>Holder for reflection information generated from shared/experiment_config.proto</summary>
  public static partial class ExperimentConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for shared/experiment_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExperimentConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5zaGFyZWQvZXhwZXJpbWVudF9jb25maWcucHJvdG8itwEKGEZvcndhcmRF",
            "eHBlcmltZW50Q29tbWFuZBJBCgxzbGF2ZUNvbW1hbmQYAiABKA4yJi5Gb3J3",
            "YXJkRXhwZXJpbWVudENvbW1hbmQuU2xhdmVDb21tYW5kSACIAQEiRwoMU2xh",
            "dmVDb21tYW5kEg4KCkNsZWFyRmxhc2gQABIOCgpRdWVyeUZsYXNoEAESFwoT",
            "U3RyZWFtRmxhc2hDb250ZW50cxACQg8KDV9zbGF2ZUNvbW1hbmQiYAoSRXhw",
            "ZXJpbWVudFJlc3BvbnNlEhgKEE1lYXN1cmVtZW50Q291bnQYASABKA0SHAoU",
            "TWVhc3VyZW1lbnRzRGlzYWJsZWQYAiABKAgSEgoKV2FzQ2xlYXJlZBgDIAEo",
            "CCIzChhNZWFzdXJlbWVudFN0cmVhbVJlcXVlc3QSFwoPRnJhZ21lbnRTaXpl",
            "TWF4GAEgASgNIhsKGU1lYXN1cmVtZW50U3RyZWFtRnJhZ21lbnQidAoVU2Vx",
            "dWVuY2VDb25maWd1cmF0aW9uEhgKEEVuYWJsZUFsd2F5c1NlbmQYASABKAgS",
            "GAoQQWx3YXlzU2VuZFBlcmlvZBgCIAEoDRIYChBMaW1pdGVkU2VuZENvdW50",
            "GAMgASgNEg0KBURlbGF5GAQgASgNInoKHFRyYW5zbWl0UmVjZWl2ZUNvbmZp",
            "Z3VyYXRpb24SDwoHVHhQb3dlchgBIAEoBRIVCg1UeFJ4QmFuZHdpZHRoGAIg",
            "ASgNEhQKDFR4UnhEYXRhUmF0ZRgDIAEoDRINCgVTZXRSeBgEIAEoCBINCgVT",
            "ZXRUeBgFIAEoCCJuChNSZWNlcHRpb25SYXRlQ29uZmlnEhcKD1BhY2tldEVy",
            "cm9yUmF0ZRgBIAEoAhIUCgxPdmVycmlkZVNlZWQYAiABKAgSDAoEU2VlZBgD",
            "IAEoDRIaChJEcm9wVXBkYXRlQ29tbWFuZHMYBCABKAgqMQoSUFJuZ0ltcGxl",
            "bWVudGF0aW9uEgsKB0xGU1JfMzIQABIOCgpYb1NoaVJvXzMyEAFCB6oCBExv",
            "UmFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LoRa.PRngImplementation), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.ForwardExperimentCommand), global::LoRa.ForwardExperimentCommand.Parser, new[]{ "SlaveCommand" }, new[]{ "SlaveCommand" }, new[]{ typeof(global::LoRa.ForwardExperimentCommand.Types.SlaveCommand) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.ExperimentResponse), global::LoRa.ExperimentResponse.Parser, new[]{ "MeasurementCount", "MeasurementsDisabled", "WasCleared" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.MeasurementStreamRequest), global::LoRa.MeasurementStreamRequest.Parser, new[]{ "FragmentSizeMax" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.MeasurementStreamFragment), global::LoRa.MeasurementStreamFragment.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.SequenceConfiguration), global::LoRa.SequenceConfiguration.Parser, new[]{ "EnableAlwaysSend", "AlwaysSendPeriod", "LimitedSendCount", "Delay" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.TransmitReceiveConfiguration), global::LoRa.TransmitReceiveConfiguration.Parser, new[]{ "TxPower", "TxRxBandwidth", "TxRxDataRate", "SetRx", "SetTx" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LoRa.ReceptionRateConfig), global::LoRa.ReceptionRateConfig.Parser, new[]{ "PacketErrorRate", "OverrideSeed", "Seed", "DropUpdateCommands" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PRngImplementation {
    [pbr::OriginalName("LFSR_32")] Lfsr32 = 0,
    [pbr::OriginalName("XoShiRo_32")] XoShiRo32 = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ForwardExperimentCommand : pb::IMessage<ForwardExperimentCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ForwardExperimentCommand> _parser = new pb::MessageParser<ForwardExperimentCommand>(() => new ForwardExperimentCommand());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ForwardExperimentCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardExperimentCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardExperimentCommand(ForwardExperimentCommand other) : this() {
      _hasBits0 = other._hasBits0;
      slaveCommand_ = other.slaveCommand_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ForwardExperimentCommand Clone() {
      return new ForwardExperimentCommand(this);
    }

    /// <summary>Field number for the "slaveCommand" field.</summary>
    public const int SlaveCommandFieldNumber = 2;
    private global::LoRa.ForwardExperimentCommand.Types.SlaveCommand slaveCommand_;
    /// <summary>
    /// Only valid if receiving slave
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LoRa.ForwardExperimentCommand.Types.SlaveCommand SlaveCommand {
      get { if ((_hasBits0 & 1) != 0) { return slaveCommand_; } else { return global::LoRa.ForwardExperimentCommand.Types.SlaveCommand.ClearFlash; } }
      set {
        _hasBits0 |= 1;
        slaveCommand_ = value;
      }
    }
    /// <summary>Gets whether the "slaveCommand" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSlaveCommand {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "slaveCommand" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSlaveCommand() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ForwardExperimentCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ForwardExperimentCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SlaveCommand != other.SlaveCommand) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSlaveCommand) hash ^= SlaveCommand.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasSlaveCommand) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SlaveCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasSlaveCommand) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SlaveCommand);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasSlaveCommand) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SlaveCommand);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ForwardExperimentCommand other) {
      if (other == null) {
        return;
      }
      if (other.HasSlaveCommand) {
        SlaveCommand = other.SlaveCommand;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            SlaveCommand = (global::LoRa.ForwardExperimentCommand.Types.SlaveCommand) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            SlaveCommand = (global::LoRa.ForwardExperimentCommand.Types.SlaveCommand) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ForwardExperimentCommand message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum SlaveCommand {
        [pbr::OriginalName("ClearFlash")] ClearFlash = 0,
        [pbr::OriginalName("QueryFlash")] QueryFlash = 1,
        [pbr::OriginalName("StreamFlashContents")] StreamFlashContents = 2,
      }

    }
    #endregion

  }

  public sealed partial class ExperimentResponse : pb::IMessage<ExperimentResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExperimentResponse> _parser = new pb::MessageParser<ExperimentResponse>(() => new ExperimentResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExperimentResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperimentResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperimentResponse(ExperimentResponse other) : this() {
      measurementCount_ = other.measurementCount_;
      measurementsDisabled_ = other.measurementsDisabled_;
      wasCleared_ = other.wasCleared_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExperimentResponse Clone() {
      return new ExperimentResponse(this);
    }

    /// <summary>Field number for the "MeasurementCount" field.</summary>
    public const int MeasurementCountFieldNumber = 1;
    private uint measurementCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MeasurementCount {
      get { return measurementCount_; }
      set {
        measurementCount_ = value;
      }
    }

    /// <summary>Field number for the "MeasurementsDisabled" field.</summary>
    public const int MeasurementsDisabledFieldNumber = 2;
    private bool measurementsDisabled_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MeasurementsDisabled {
      get { return measurementsDisabled_; }
      set {
        measurementsDisabled_ = value;
      }
    }

    /// <summary>Field number for the "WasCleared" field.</summary>
    public const int WasClearedFieldNumber = 3;
    private bool wasCleared_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool WasCleared {
      get { return wasCleared_; }
      set {
        wasCleared_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExperimentResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExperimentResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MeasurementCount != other.MeasurementCount) return false;
      if (MeasurementsDisabled != other.MeasurementsDisabled) return false;
      if (WasCleared != other.WasCleared) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MeasurementCount != 0) hash ^= MeasurementCount.GetHashCode();
      if (MeasurementsDisabled != false) hash ^= MeasurementsDisabled.GetHashCode();
      if (WasCleared != false) hash ^= WasCleared.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MeasurementCount != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MeasurementCount);
      }
      if (MeasurementsDisabled != false) {
        output.WriteRawTag(16);
        output.WriteBool(MeasurementsDisabled);
      }
      if (WasCleared != false) {
        output.WriteRawTag(24);
        output.WriteBool(WasCleared);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MeasurementCount != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MeasurementCount);
      }
      if (MeasurementsDisabled != false) {
        output.WriteRawTag(16);
        output.WriteBool(MeasurementsDisabled);
      }
      if (WasCleared != false) {
        output.WriteRawTag(24);
        output.WriteBool(WasCleared);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MeasurementCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MeasurementCount);
      }
      if (MeasurementsDisabled != false) {
        size += 1 + 1;
      }
      if (WasCleared != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExperimentResponse other) {
      if (other == null) {
        return;
      }
      if (other.MeasurementCount != 0) {
        MeasurementCount = other.MeasurementCount;
      }
      if (other.MeasurementsDisabled != false) {
        MeasurementsDisabled = other.MeasurementsDisabled;
      }
      if (other.WasCleared != false) {
        WasCleared = other.WasCleared;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MeasurementCount = input.ReadUInt32();
            break;
          }
          case 16: {
            MeasurementsDisabled = input.ReadBool();
            break;
          }
          case 24: {
            WasCleared = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MeasurementCount = input.ReadUInt32();
            break;
          }
          case 16: {
            MeasurementsDisabled = input.ReadBool();
            break;
          }
          case 24: {
            WasCleared = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MeasurementStreamRequest : pb::IMessage<MeasurementStreamRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MeasurementStreamRequest> _parser = new pb::MessageParser<MeasurementStreamRequest>(() => new MeasurementStreamRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MeasurementStreamRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeasurementStreamRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeasurementStreamRequest(MeasurementStreamRequest other) : this() {
      fragmentSizeMax_ = other.fragmentSizeMax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeasurementStreamRequest Clone() {
      return new MeasurementStreamRequest(this);
    }

    /// <summary>Field number for the "FragmentSizeMax" field.</summary>
    public const int FragmentSizeMaxFieldNumber = 1;
    private uint fragmentSizeMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FragmentSizeMax {
      get { return fragmentSizeMax_; }
      set {
        fragmentSizeMax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MeasurementStreamRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MeasurementStreamRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FragmentSizeMax != other.FragmentSizeMax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FragmentSizeMax != 0) hash ^= FragmentSizeMax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FragmentSizeMax != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FragmentSizeMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FragmentSizeMax != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FragmentSizeMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FragmentSizeMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FragmentSizeMax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MeasurementStreamRequest other) {
      if (other == null) {
        return;
      }
      if (other.FragmentSizeMax != 0) {
        FragmentSizeMax = other.FragmentSizeMax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FragmentSizeMax = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            FragmentSizeMax = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Payload in generic bytes field
  /// </summary>
  public sealed partial class MeasurementStreamFragment : pb::IMessage<MeasurementStreamFragment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MeasurementStreamFragment> _parser = new pb::MessageParser<MeasurementStreamFragment>(() => new MeasurementStreamFragment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MeasurementStreamFragment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeasurementStreamFragment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeasurementStreamFragment(MeasurementStreamFragment other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MeasurementStreamFragment Clone() {
      return new MeasurementStreamFragment(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MeasurementStreamFragment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MeasurementStreamFragment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MeasurementStreamFragment other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class SequenceConfiguration : pb::IMessage<SequenceConfiguration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SequenceConfiguration> _parser = new pb::MessageParser<SequenceConfiguration>(() => new SequenceConfiguration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SequenceConfiguration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequenceConfiguration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequenceConfiguration(SequenceConfiguration other) : this() {
      enableAlwaysSend_ = other.enableAlwaysSend_;
      alwaysSendPeriod_ = other.alwaysSendPeriod_;
      limitedSendCount_ = other.limitedSendCount_;
      delay_ = other.delay_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SequenceConfiguration Clone() {
      return new SequenceConfiguration(this);
    }

    /// <summary>Field number for the "EnableAlwaysSend" field.</summary>
    public const int EnableAlwaysSendFieldNumber = 1;
    private bool enableAlwaysSend_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EnableAlwaysSend {
      get { return enableAlwaysSend_; }
      set {
        enableAlwaysSend_ = value;
      }
    }

    /// <summary>Field number for the "AlwaysSendPeriod" field.</summary>
    public const int AlwaysSendPeriodFieldNumber = 2;
    private uint alwaysSendPeriod_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AlwaysSendPeriod {
      get { return alwaysSendPeriod_; }
      set {
        alwaysSendPeriod_ = value;
      }
    }

    /// <summary>Field number for the "LimitedSendCount" field.</summary>
    public const int LimitedSendCountFieldNumber = 3;
    private uint limitedSendCount_;
    /// <summary>
    /// Ignored if EnableAlwaysSend is true
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LimitedSendCount {
      get { return limitedSendCount_; }
      set {
        limitedSendCount_ = value;
      }
    }

    /// <summary>Field number for the "Delay" field.</summary>
    public const int DelayFieldNumber = 4;
    private uint delay_;
    /// <summary>
    /// Apply a DelayMs before the config goes into effect
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Delay {
      get { return delay_; }
      set {
        delay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SequenceConfiguration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SequenceConfiguration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnableAlwaysSend != other.EnableAlwaysSend) return false;
      if (AlwaysSendPeriod != other.AlwaysSendPeriod) return false;
      if (LimitedSendCount != other.LimitedSendCount) return false;
      if (Delay != other.Delay) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EnableAlwaysSend != false) hash ^= EnableAlwaysSend.GetHashCode();
      if (AlwaysSendPeriod != 0) hash ^= AlwaysSendPeriod.GetHashCode();
      if (LimitedSendCount != 0) hash ^= LimitedSendCount.GetHashCode();
      if (Delay != 0) hash ^= Delay.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EnableAlwaysSend != false) {
        output.WriteRawTag(8);
        output.WriteBool(EnableAlwaysSend);
      }
      if (AlwaysSendPeriod != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AlwaysSendPeriod);
      }
      if (LimitedSendCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(LimitedSendCount);
      }
      if (Delay != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Delay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EnableAlwaysSend != false) {
        output.WriteRawTag(8);
        output.WriteBool(EnableAlwaysSend);
      }
      if (AlwaysSendPeriod != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(AlwaysSendPeriod);
      }
      if (LimitedSendCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(LimitedSendCount);
      }
      if (Delay != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Delay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EnableAlwaysSend != false) {
        size += 1 + 1;
      }
      if (AlwaysSendPeriod != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AlwaysSendPeriod);
      }
      if (LimitedSendCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LimitedSendCount);
      }
      if (Delay != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Delay);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SequenceConfiguration other) {
      if (other == null) {
        return;
      }
      if (other.EnableAlwaysSend != false) {
        EnableAlwaysSend = other.EnableAlwaysSend;
      }
      if (other.AlwaysSendPeriod != 0) {
        AlwaysSendPeriod = other.AlwaysSendPeriod;
      }
      if (other.LimitedSendCount != 0) {
        LimitedSendCount = other.LimitedSendCount;
      }
      if (other.Delay != 0) {
        Delay = other.Delay;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EnableAlwaysSend = input.ReadBool();
            break;
          }
          case 16: {
            AlwaysSendPeriod = input.ReadUInt32();
            break;
          }
          case 24: {
            LimitedSendCount = input.ReadUInt32();
            break;
          }
          case 32: {
            Delay = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EnableAlwaysSend = input.ReadBool();
            break;
          }
          case 16: {
            AlwaysSendPeriod = input.ReadUInt32();
            break;
          }
          case 24: {
            LimitedSendCount = input.ReadUInt32();
            break;
          }
          case 32: {
            Delay = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TransmitReceiveConfiguration : pb::IMessage<TransmitReceiveConfiguration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransmitReceiveConfiguration> _parser = new pb::MessageParser<TransmitReceiveConfiguration>(() => new TransmitReceiveConfiguration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TransmitReceiveConfiguration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransmitReceiveConfiguration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransmitReceiveConfiguration(TransmitReceiveConfiguration other) : this() {
      txPower_ = other.txPower_;
      txRxBandwidth_ = other.txRxBandwidth_;
      txRxDataRate_ = other.txRxDataRate_;
      setRx_ = other.setRx_;
      setTx_ = other.setTx_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TransmitReceiveConfiguration Clone() {
      return new TransmitReceiveConfiguration(this);
    }

    /// <summary>Field number for the "TxPower" field.</summary>
    public const int TxPowerFieldNumber = 1;
    private int txPower_;
    /// <summary>
    /// TX power, BW and SF
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TxPower {
      get { return txPower_; }
      set {
        txPower_ = value;
      }
    }

    /// <summary>Field number for the "TxRxBandwidth" field.</summary>
    public const int TxRxBandwidthFieldNumber = 2;
    private uint txRxBandwidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TxRxBandwidth {
      get { return txRxBandwidth_; }
      set {
        txRxBandwidth_ = value;
      }
    }

    /// <summary>Field number for the "TxRxDataRate" field.</summary>
    public const int TxRxDataRateFieldNumber = 3;
    private uint txRxDataRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TxRxDataRate {
      get { return txRxDataRate_; }
      set {
        txRxDataRate_ = value;
      }
    }

    /// <summary>Field number for the "SetRx" field.</summary>
    public const int SetRxFieldNumber = 4;
    private bool setRx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SetRx {
      get { return setRx_; }
      set {
        setRx_ = value;
      }
    }

    /// <summary>Field number for the "SetTx" field.</summary>
    public const int SetTxFieldNumber = 5;
    private bool setTx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SetTx {
      get { return setTx_; }
      set {
        setTx_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TransmitReceiveConfiguration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TransmitReceiveConfiguration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TxPower != other.TxPower) return false;
      if (TxRxBandwidth != other.TxRxBandwidth) return false;
      if (TxRxDataRate != other.TxRxDataRate) return false;
      if (SetRx != other.SetRx) return false;
      if (SetTx != other.SetTx) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TxPower != 0) hash ^= TxPower.GetHashCode();
      if (TxRxBandwidth != 0) hash ^= TxRxBandwidth.GetHashCode();
      if (TxRxDataRate != 0) hash ^= TxRxDataRate.GetHashCode();
      if (SetRx != false) hash ^= SetRx.GetHashCode();
      if (SetTx != false) hash ^= SetTx.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TxPower != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TxPower);
      }
      if (TxRxBandwidth != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TxRxBandwidth);
      }
      if (TxRxDataRate != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TxRxDataRate);
      }
      if (SetRx != false) {
        output.WriteRawTag(32);
        output.WriteBool(SetRx);
      }
      if (SetTx != false) {
        output.WriteRawTag(40);
        output.WriteBool(SetTx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TxPower != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TxPower);
      }
      if (TxRxBandwidth != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(TxRxBandwidth);
      }
      if (TxRxDataRate != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TxRxDataRate);
      }
      if (SetRx != false) {
        output.WriteRawTag(32);
        output.WriteBool(SetRx);
      }
      if (SetTx != false) {
        output.WriteRawTag(40);
        output.WriteBool(SetTx);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TxPower != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TxPower);
      }
      if (TxRxBandwidth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TxRxBandwidth);
      }
      if (TxRxDataRate != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TxRxDataRate);
      }
      if (SetRx != false) {
        size += 1 + 1;
      }
      if (SetTx != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TransmitReceiveConfiguration other) {
      if (other == null) {
        return;
      }
      if (other.TxPower != 0) {
        TxPower = other.TxPower;
      }
      if (other.TxRxBandwidth != 0) {
        TxRxBandwidth = other.TxRxBandwidth;
      }
      if (other.TxRxDataRate != 0) {
        TxRxDataRate = other.TxRxDataRate;
      }
      if (other.SetRx != false) {
        SetRx = other.SetRx;
      }
      if (other.SetTx != false) {
        SetTx = other.SetTx;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TxPower = input.ReadInt32();
            break;
          }
          case 16: {
            TxRxBandwidth = input.ReadUInt32();
            break;
          }
          case 24: {
            TxRxDataRate = input.ReadUInt32();
            break;
          }
          case 32: {
            SetRx = input.ReadBool();
            break;
          }
          case 40: {
            SetTx = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TxPower = input.ReadInt32();
            break;
          }
          case 16: {
            TxRxBandwidth = input.ReadUInt32();
            break;
          }
          case 24: {
            TxRxDataRate = input.ReadUInt32();
            break;
          }
          case 32: {
            SetRx = input.ReadBool();
            break;
          }
          case 40: {
            SetTx = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ReceptionRateConfig : pb::IMessage<ReceptionRateConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReceptionRateConfig> _parser = new pb::MessageParser<ReceptionRateConfig>(() => new ReceptionRateConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReceptionRateConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LoRa.ExperimentConfigReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReceptionRateConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReceptionRateConfig(ReceptionRateConfig other) : this() {
      packetErrorRate_ = other.packetErrorRate_;
      overrideSeed_ = other.overrideSeed_;
      seed_ = other.seed_;
      dropUpdateCommands_ = other.dropUpdateCommands_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReceptionRateConfig Clone() {
      return new ReceptionRateConfig(this);
    }

    /// <summary>Field number for the "PacketErrorRate" field.</summary>
    public const int PacketErrorRateFieldNumber = 1;
    private float packetErrorRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PacketErrorRate {
      get { return packetErrorRate_; }
      set {
        packetErrorRate_ = value;
      }
    }

    /// <summary>Field number for the "OverrideSeed" field.</summary>
    public const int OverrideSeedFieldNumber = 2;
    private bool overrideSeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OverrideSeed {
      get { return overrideSeed_; }
      set {
        overrideSeed_ = value;
      }
    }

    /// <summary>Field number for the "Seed" field.</summary>
    public const int SeedFieldNumber = 3;
    private uint seed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Seed {
      get { return seed_; }
      set {
        seed_ = value;
      }
    }

    /// <summary>Field number for the "DropUpdateCommands" field.</summary>
    public const int DropUpdateCommandsFieldNumber = 4;
    private bool dropUpdateCommands_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DropUpdateCommands {
      get { return dropUpdateCommands_; }
      set {
        dropUpdateCommands_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReceptionRateConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReceptionRateConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PacketErrorRate, other.PacketErrorRate)) return false;
      if (OverrideSeed != other.OverrideSeed) return false;
      if (Seed != other.Seed) return false;
      if (DropUpdateCommands != other.DropUpdateCommands) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PacketErrorRate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PacketErrorRate);
      if (OverrideSeed != false) hash ^= OverrideSeed.GetHashCode();
      if (Seed != 0) hash ^= Seed.GetHashCode();
      if (DropUpdateCommands != false) hash ^= DropUpdateCommands.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PacketErrorRate != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PacketErrorRate);
      }
      if (OverrideSeed != false) {
        output.WriteRawTag(16);
        output.WriteBool(OverrideSeed);
      }
      if (Seed != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Seed);
      }
      if (DropUpdateCommands != false) {
        output.WriteRawTag(32);
        output.WriteBool(DropUpdateCommands);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PacketErrorRate != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(PacketErrorRate);
      }
      if (OverrideSeed != false) {
        output.WriteRawTag(16);
        output.WriteBool(OverrideSeed);
      }
      if (Seed != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Seed);
      }
      if (DropUpdateCommands != false) {
        output.WriteRawTag(32);
        output.WriteBool(DropUpdateCommands);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PacketErrorRate != 0F) {
        size += 1 + 4;
      }
      if (OverrideSeed != false) {
        size += 1 + 1;
      }
      if (Seed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Seed);
      }
      if (DropUpdateCommands != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReceptionRateConfig other) {
      if (other == null) {
        return;
      }
      if (other.PacketErrorRate != 0F) {
        PacketErrorRate = other.PacketErrorRate;
      }
      if (other.OverrideSeed != false) {
        OverrideSeed = other.OverrideSeed;
      }
      if (other.Seed != 0) {
        Seed = other.Seed;
      }
      if (other.DropUpdateCommands != false) {
        DropUpdateCommands = other.DropUpdateCommands;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            PacketErrorRate = input.ReadFloat();
            break;
          }
          case 16: {
            OverrideSeed = input.ReadBool();
            break;
          }
          case 24: {
            Seed = input.ReadUInt32();
            break;
          }
          case 32: {
            DropUpdateCommands = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            PacketErrorRate = input.ReadFloat();
            break;
          }
          case 16: {
            OverrideSeed = input.ReadBool();
            break;
          }
          case 24: {
            Seed = input.ReadUInt32();
            break;
          }
          case 32: {
            DropUpdateCommands = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
